---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaostoolkit-kopf-crd-watcher
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - zalando.org
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - delete
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - pods
  verbs:
  - create
  - get
  - delete
  - list
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - list
- apiGroups:
  - chaostoolkit.org
  resources:
  - chaosexperiments
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - list
  - get
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaostoolkit-kopf-crd-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaostoolkit-kopf-crd-watcher
subjects:
- kind: ServiceAccount
  name: chaostoolkit-crd
  namespace: chaostoolkit-crd
