dist: xenial
language: python
python:
- 3.7
before_install:
- curl  https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
  -o kustomize_v3.5.4_linux_amd64.tar.gz -s -O -L
- tar xzf kustomize_v3.5.4_linux_amd64.tar.gz
- export PATH=.:$PATH
- kustomize version
install:
- pip install -r requirements.txt -r requirements-dev.txt
services:
- docker
env:
  global:
  - DOCKER_USER_NAME: chaostoolkit
  - secure: JpVlzIgw0LWWkKEmExcOxjI9wEAJ2wOVMDNizbtkpaMMT6nPppxKKa+mp0HZNXItCfwNPlhY2iyjxzi1yB0xKi87FTfmDz4qjCTz6mAU6Q2tWc31HMrs2YeXGmDjXMFc17dQvM3y1XKxkjUGr5kIYTn3T3dO4ZmdVQ8Mqt/O2vdI8QoQfK8N25vJ5NhpTLgCQepv3pfD1xgV5zOU3If8sHisgR1JtqCznI9uTB6gfPaiLA7qIh4ToUEU8Uuvzn8VLRQ5SucaldmPtyJoymthzTT1dpT/e5y2CnSPtZ4SnssNFZsEzzMcxYl7SBvOiwlhaELu4IPVGViXbvXK6I/S1g1reC3GYdZ708jCS7z0cjmT8lnQQ/s8y4X6ulQn55ENWSHR2dFibcoAnbVmBVpgy8T7d6G4WBxo+k5v4wmwTYiMZREf2Gh7oxG40cXivNE02mPExc4HfEUiiB2joqhE0tjJHKqPy6kz/vC7qn4f89x22hspKG0qQveG0EV2S2pK1WMqjj/M2vD3nS/5nt0EpbYdKgEJw9ki8+jmytCDpe1oiwNEbY3JdW2pA5M+Y20QSByJ26X4R2FHSj9ZJFo+viaHU9UiFnRBArcTWuE01fX+MYp+sOIhC53X0he5HuXnXT6/qSYN8mJGVT/Cx8kcn4OwZo6TVi7exSMMLjGI7uI=

script:
- bash ci.bash
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
