---
- name: build, tag, push, and deploy from web/dist
  hosts:
    - localhost
  tasks:
    - name: build docker image
      docker_image:
        build:
          path: "."
          pull: no
        name: paterw00t.com/chaostoolkit-k8scrd
        tag: "latest"
        push: true
        source: build
