---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chaosexperiments.chaostoolkit.org
spec:
  scope: Namespaced
  group: chaostoolkit.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: ChaosToolkitExperiment
    plural: chaosexperiments
    singular: chaosexperiment
    shortNames:
      - ctk
      - ctks
